server:
  port: 8080
spring:
  application:
    name: RevOverflow-GatewayService
  cloud:
    gateway:
      routes:
      # ======================
      - id: RevOverflow-UserService
        uri: lb://user
        predicates:
        - Path=/user/**
      # ======================
      - id: RevOverflow-QuestionService
        uri: lb://question
        predicates:
        - Path=/question/**
      # ======================
      - id: RevOverflow-AnswerService
        uri: lb://answer
        predicates:
        - Path=/answer/**